#!/usr/bin/python

import os
import sys

'''
folderName = sys.argv[1]
path = os.getcwd()
checkExist = os.path.exists(path + "/" + folderName)
# print(checkExist)
if checkExist == True:
	print("Error, folder/file exists")
else:
	os.mkdir(folderName)
	print("Folder/file created")
'''

path = os.getcwd()
if sys.argv[1] == "-p":	
	for item in sys.argv:
		# print(item)
		checkExist = os.path.exists(path + "/" + item)
		if checkExist == True:
			print("Error, folder/file exists")
		else:
			os.mkdir(item)
			print("Folder/file created")
else:
	for item in sys.argv:
		# print(item)
		checkExist = os.path.exists(path + "/" + item)
		if checkExist == True:
			print("Error, folder/file exists")
		else:
			os.mkdir(item)
			print("Folder/file created")
