#!/usr/bin/python

import os

# print(os.getcwd())
# os.chdir("/proc")
# print(os.getcwd())

p = open('running_processes', 'a')

psname = ""
pid = ""
psname_id_text = "PID, Name"

for process in os.listdir("/proc"):
	# print(process)
	if process.isdigit():
		# print("True")
		os.chdir("/proc/"+process)
		f = open("/proc/"+process+"/status", "r")
		for line in f:
			if line.startswith("Name"):
				# print(line[6:])
				psname = line[6:-1]
				pid = process
				# print(psname,  process)
				psname_id = pid + ", " + psname + "\n"
				# print(psname_id)
				psname_id_text += psname_id
		f.close()

print(psname_id_text)
p.write(psname_id_text)
p.close()
